#pragma once

// Generated by tools/run_lqr_sim.py from the committed seeded model.
// Do not tune this header by hand; change the sim/controller inputs and regenerate it.
namespace FinnLqrSeeded {
constexpr char kModelSha256[] = "4a85ddfeea07";
constexpr unsigned long kControlPeriodUs = 10000UL;
constexpr float kWheelRadiusM = 0.081f;
constexpr float kTorqueLimitNm = 1.0f;
constexpr float kTargetPitchRad = 0.0411449906f;
constexpr float kTargetForwardVelMS = 0.0f;
constexpr float kPositionHoldKpS = 0.15f;
constexpr float kMaxPositionCorrectionMS = 0.15f;
constexpr float kGainPitch = 61.8993272f;
constexpr float kGainPitchRate = 9.56442891f;
constexpr float kGainForwardVel = 13.0267381f;
constexpr int kPitchAxis = 0;
constexpr float kPitchSign = 1.0f;
constexpr float kForwardAccelSign = -1.0f;
constexpr float kRealLeftEncoderForwardSign = 1.0f;
constexpr float kRealRightEncoderForwardSign = 1.0f;
constexpr bool kWheelEncoderDirectionsBenchVerified = false;
constexpr float kRealLeftCommonTorqueSign = 1.0f;
constexpr float kRealRightCommonTorqueSign = 1.0f;
constexpr bool kPitchDirectionBenchVerified = false;

// Steering and the command layer above the always-on balance loop.
// Firmware that ignores everything below still balances as validated.
constexpr int kYawAxis = 1;
constexpr float kYawSign = 1.0f;
constexpr float kGainYawRate = 5.71421979f;
constexpr float kRealLeftActuatorYawSign = -1.0f;
constexpr float kMaxForwardVelMS = 0.6f;
constexpr float kMaxYawRateRadS = 1.0f;
constexpr float kDriveAccelLimitMS2 = 0.5f;
constexpr float kDriveYawAccelLimitRadS2 = 3.0f;
constexpr unsigned long kCommandTimeoutMs = 500UL;
constexpr float kRefPositionBandM = 0.3f;
constexpr bool kYawDirectionBenchVerified = false;
}  // namespace FinnLqrSeeded
