
[platformio]
src_dir = src
default_envs = bringup_imu_can

[env]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
    adafruit/Adafruit BNO08x
    https://github.com/tonton81/FlexCAN_T4.git

[env:main]
; eventual main firmware, not used for bring up

[env:bringup_imu_can]
build_src_filter = -<*> +<../bringup/01_imu_can_check>
; excludes src/ and pulls in the bringup code for testing the IMU and CAN bus